### ISSUE TITLE
Security : username 변수가 갑자기 어디서?

### ISSUE THREAD

**Issue by civiltec** [onlybooks/spring-boot-reactive#4]
안녕하세요 ^^
9장 보안에서 p279 의
public ReactiveUserDetailsService .... {
   return username -> ...
}
이 부분의 질문입니다.
갑자기 뜬금없이 username 이 나와서 황당합니다. ^^ , class의 member 변수인가 해서 원문을 찾아 보아도 없군요 ^^
이런 문법이 java에 있으려면, username 이 global 변수?, 책에선 인자로 받는다고 서술되어 있는데 원문 소스에도 없어서요.
어디에 import 되어 있는지 모르겠습니다.
감사합니다. ^^~

**Comment by HomoEfficio** [comment]
안녕하세요.

`username -> ...`은 자바8 에 도입된 람다식(Lambda Expression) 입니다.  
username 은 람다식의 파라미터 이름으로서 일반적인 변수명 짓는 것처럼 임의로 정할 수 있습니다.

p279 코드는 아래와 같고요,

```java
@Configuration
public class SecurityConfig {

	@Bean
	public ReactiveUserDetailsService userDetailsService(UserRepository repository) { // <1>
		return username -> repository.findByName(username) // <2>
				.map(user -> User.withDefaultPasswordEncoder() // <3>
						.username(user.getName()) //
						.password(user.getPassword()) //
						.authorities(user.getRoles().toArray(new String[0])) //
						.build()); // <4>
	}
	
	...
```

결론적으로 userDetailsService 메서드는 ReactiveUserDetailsService 타입을 반환해야 하는데, ReactiveUserDetailsService 은 다음과 같이 메서드가 1개인 Functional Interface 입니다.

```java
package org.springframework.security.core.userdetails;

import reactor.core.publisher.Mono;

public interface ReactiveUserDetailsService {
    Mono<UserDetails> findByUsername(String var1);
}

```

결국 유일한 메서드인 findByUsername 의 signiture에 맞게 String 1개를 받아서 `Mono<UserDetails>`를 반환하는 람다식을 반환해주면 되고, 그 람다식이 바로 `username -> ...`으로 시작하는 람다식입니다.

**Comment by civiltec** [comment]
감사합니다. ^^

람다식은 꽤 오래 사용해 보아서 안다고 생각했는데, 
Functional Interface 라는 것이 있는 줄은 처음 알았네요 ^^
....
친절한 답변, 감사드립니다. ^^
늘 행복하세요 ^^~
